services:
  - type: web
    name: dairy-management-system
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: JWT_KEY
        generateValue: true
      - key: JWT_ISSUER
        value: DairyManagement
      - key: JWT_AUDIENCE
        value: DairyUsers